### ISSUE TITLE
don't hard-code path to Ceylon

### ISSUE THREAD

**Issue by jvasileff** [DiegoCoronel/ceylon-spring-boot#2]
Currently, `gradle compileCeylon --stacktrace` results in:

```
IOException: Cannot run program "/Users/DiegoCoronel/Work/Git/ceylon/ceylon/dist/dist/bin/ceylon"
```

**Comment by DiegoCoronel** [comment]
Fixed by 56413c2edaf149f289f395dead0db06865fe496d , but i still need to add some documentation about this in README because it currently needs master version (1.2.3). Tks @jvasileff
